### ISSUE TITLE
Window Object Implementation (window_t)

### ISSUE THREAD

**Issue by wpumacay** [wpumacay/loco_renderer#15]
# Description

This keeps track of the implementation of the **`window_t`** objects, required for creating a window and setting up an appropriate OpenGL context.

## Tasks
- [x] Implementation of **`window_t`** and **`window_impl_t`** interface
- [x] Implementation of the impl for **GLFW** **`window_impl_glfw`**, using GLFW as windowing backend
- [x] Implementation of the impl for **EGL** **`window_impl_egl`**, using EGL to create a rendering context and drawing surface
- [x] ~~Implementation of the impl for **OSMESA** **`window_impl_osmesa`**, using OSMesa for creating a context (software-based off-screen rendering)~~
- [x] Create an **`example`** of its usage
- [x] Create **`python`** bindings for `window_t` object
- [x] Add documentation related to its usage

**Comment by wpumacay** [comment]
Need to update the callback for the keyboard, adding an extra entry for the **`mode`** (`shift`, `ctrl`, etc.)

```c++
// Use keyboard callback with (`key`, `action`, `mode`)
using KeyboardCallback = std::function<void(int, int, int)>;
```

**Comment by wpumacay** [comment]
Python bindings were added in this commit: bedd7e3. So far, the usage on python land is the following:

```python
import renderer

# Create the properties struct (used to configure the window)
properties = renderer.WindowProperties()
properties.title = "some-descriptive-window-title"
properties.width = 800 # some appropriate window width
properties.height = 600 # some appropriate window height
properties.backend = renderer.eWindowBackend.TYPE_GLFW

# Create a window with the previous configuration
window = renderer.Window(properties)

# Some simple render loop
while window.active:
  window.Begin()
  # some GL stuff here
  window.End()
```

So far this API seems ok, but it would be better to avoid constructing a config struct before constructing the actual object we require (`window_t` object in this case). Might consider adding a second constructor for the `Window` object.

**Comment by wpumacay** [comment]
Commit 559797ca7f8651bab7b46ec4c8b6b53fa8109ff2 adds some simple docs for the window class. Will improve them in later commits, as those docs are just the starting point

**Comment by wpumacay** [comment]
Commit 1cdbcd0cdaf7b34067954fe2578010172cc06ae4 adds support for egl for off-screen rendering. Will have to add a more detailed example though in the following commits (using `glReadPixels` and the `tga` format, as in [this][0] example).

Note that we also require to check if there's EGL support. Otherwise, we should treat the  EGL impl as empty (preprocessor magic)

[0]: <https://github.com/Jba03/glReadPixels_example> (glreadpixels-example)

**Comment by wpumacay** [comment]
Removed `osmesa` related code, as will add this feature in a later stage (need to find some examples I lost somewhere :c )

**Comment by wpumacay** [comment]
Closed by #16
