### ISSUE TITLE
Shader (shader_t) and Program (program_t) Objects

### ISSUE THREAD

**Issue by wpumacay** [wpumacay/loco_renderer#3]
# Description

This tracks the implementation of the `Shader` and `Program` classes, which are in charge of handling shaders compilation, linking, and other related functionalities required from **OpenGL glsl-based shaders**

## Tasks
- [x] Implement **`shader_t`** and **`program_t`** classes
- [x] Create an **`example`** of its usage
- [ ] ~~Implement some **`unittests`**~~
- [x] Implement **`python`** bindings
- [x] Make **`documentation`** explaining its usage

## Notes

* There's the legacy implementations of both [`shader`][0] and [`program`][0], which we can use as starting point.
* There's a legacy [`example`][2] of its usage; however, we'd prefer to update the API to make sure its usage is simpler both in **`c++`** and **`python`** lands.
* Notice that `shader_t` objects are going to be part of the material itself (as in other rendering engines like Ogre3d and ThreeJS). Keep this in mind to handle the ownership contract that these objects must satisfy.

[0]: <https://github.com/wpumacay/loco_renderer/blob/legacy/legacy/include/shaders/CShader.h> (legacy-reference-impl-1)
[1]:
<https://github.com/wpumacay/loco_renderer/blob/legacy/legacy/include/shaders/CProgram.h> (legacy-reference-impl-2)
[2]:
<https://github.com/wpumacay/loco_renderer/blob/legacy/legacy/examples/cpp/core/sample_shaders.cpp> (legacy-reference-example-1)

**Comment by wpumacay** [comment]
Finished implementations of `shader_t` and `program_t` on commit 6ae107a

**Comment by wpumacay** [comment]
Closed by #17
